In [1]:
import pickle
import tensorflow as tf
import numpy as np

In [2]:
params = 'Temperature'
dataset_size = 'small'


In [3]:
data

NameError: name 'data' is not defined

In [4]:
len(data)

NameError: name 'data' is not defined

In [5]:
data = np.array(data)

x = data
y = np.roll(x,-1,axis=0)

# print(x[1])
# print()
# print(y[0])

value = 1
for ori in range(len(x)-1):
    if not value:
        break
    # print(ori)
    ttt = x[ori+1]
    fff = y[ori]
    fin = ttt==fff
    for g in fin:
        for h in g:
            if h == False:
                print('MARHA')
                value = 0
                break

if value:
    print('GUD')
    
size = len(x)
test = 0.1
valid = 0.1
train = x[:-(size * (test+valid))]
valid = x[-(size * (test+valid)): -size*test]
test = x[-size*test:]

NameError: name 'data' is not defined

In [9]:
def create_dataset(dataset_size='small', params='Temperature'):
    # preparing path
    if dataset_size == 'small':
        dirr = '32x32'
    elif dataset_size == 'large':
        dirr = '64x64'
    else:
        dirr = '131x151'
    # TODO: logic for parameters of dataset
    
    # create name based on arguments [local path]
    path = '../PARSED/' + dirr + '/' + params + '.pkl'
    
    #loading dataset
    with open(path, 'rb') as f:
        data = pickle.load(f, encoding='latin1')

    return data

In [4]:
def shift_dataset(data, steps=1):
    return np.roll(data,-1*steps,axis=0)

In [5]:
def split_dataset(data, valid=0.1, test=0.1):
    x = data
    
    size = len(x)
    # split
    train_features = x[:int(-(size * (test+valid)))]
    valid_features= x[int(-(size * (test+valid))): int(-size*test)]
    test_features = x[int(-size*test):]
    
    return train_features, valid_features, test_features

In [6]:
# around 0 => -3 -- 3 (~)
def normalize_v1(data):
    mean_data = np.mean(data)
    std_data = np.std(data)
    norm_data = (data-mean_data) / std_data
    return norm_data, mean_data, std_data

def denormalize_v1(data, mean, std):
    data *= std
    data += mean
    
    return data

In [7]:
# around 0 => -0.5 -- 0.5
def normalize_v2(data):
    minn = np.amin(data)
    maxx = np.amax(data)
    
    normalized = (data - minn) / (maxx - minn)
    normalized -= 0.5
    return normalized, minn, maxx

def denormalize_v2(data, minn, maxx):
    diff = maxx - minn
    
    data += 0.5
    denormalized = (data * diff) + minn
    return denormalized

In [10]:
dat_x = create_dataset()
print('DEFAULT')
print(dat_x[0])

normal, minn, maxx = normalize_v2(dat_x)
print('NORMALIZED')
print(normal[0])
print(np.amax(normal), np.amin(normal))

back2future = denormalize_v2(normal, minn, maxx)
print('DENORMALIZED')
print(back2future[0])

DEFAULT
[[276.45422 276.27136 276.13416 ... 273.79114 273.47766 273.16052]
 [276.63147 276.53528 276.4923  ... 273.63245 273.39514 273.22815]
 [276.56458 276.43884 276.42126 ... 273.75012 273.67908 273.63293]
 ...
 [281.56726 283.51086 283.5614  ... 277.09338 276.93567 275.0387 ]
 [282.6969  283.96326 283.31458 ... 276.64856 275.33777 273.17468]
 [283.42688 283.95837 283.64612 ... 275.30994 273.61536 272.9718 ]]
NORMALIZED
[[-0.01992336 -0.02280152 -0.02496111 ... -0.06183913 -0.06677312
  -0.07176474]
 [-0.01713359 -0.01864761 -0.01932392 ... -0.06433687 -0.06807193
  -0.07070032]
 [-0.01818648 -0.02016544 -0.02044213 ... -0.06248471 -0.06360292
  -0.06432918]
 ...
 [ 0.06055355  0.09114498  0.0919404  ... -0.00986329 -0.01234564
  -0.04220313]
 [ 0.07833356  0.09826541  0.08805549 ... -0.0168646  -0.03749585
  -0.07154188]
 [ 0.08982307  0.09818858  0.09327382 ... -0.03793392 -0.06460586
  -0.07473511]]
0.5 -0.5
DENORMALIZED
[[276.45422 276.27136 276.13416 ... 273.79114 273.47766 273

In [16]:
def next_batch(data_array):
    length=data_array.shape[0] #assuming the data array to be a np arry
    permutations=np.random.permutation(length)
    idxs=permutations[0:batch_size]
    batch=np.zeros([batch_size, C, img_size*channel], dtype=np.float32)
    for i in range(len(idxs)):
        batch[i,:]=data_array[idxs[i]].reshape(C,img_size*channel)
    return batch / 255.

In [17]:
batch_size = 24
img_size = 32*32
channel = 1
C = 1

ddd = next_batch(t_f)

NameError: name 't_f' is not defined

In [12]:
data_train, valid, test = split_dataset(dat_x, valid=0, test=0.1)

In [17]:
len(data_train)

7906

In [14]:
valid

[]

In [18]:
len(test)

878

In [19]:
len(dat_x)

8784

In [21]:
7906 + 878

8784

In [22]:
with open('train_temp_32.pkl','wb') as f:
    pickle.dump(data_train, f, pickle.HIGHEST_PROTOCOL)

In [23]:
with open('test_temp_32.pkl','wb') as f:
    pickle.dump(test, f, pickle.HIGHEST_PROTOCOL)